[versions]
androidx-junit = "1.1.5"
compose-bom = "2023.09.01"
espressoCore = "3.5.1"
firebase-bom = "32.5.0"
firebase-crashlytics = "2.9.9"
composeKotlinCompiler = "1.5.3"
gms = "4.4.0"
agp = "8.1.1"
junit = "4.13.2"
kotlin = "1.9.10"
hilt = "2.47"
androidx-hilt = "1.1.0"
appcompat = "1.6.1"
core-ktx = "1.12.0"
startup = "1.1.1"
striktCore = "0.34.0"
timber = "5.0.1"
datastore-prefs = "1.0.0"
activity-compose = "1.8.0"
room = "2.6.0"
sqlite = "2.4.0"
navigation = "2.7.4"
lifecycle = "2.6.2"
work = "2.8.1"
desugar = "1.1.5"
crypto = "1.0.0"
coil = "2.4.0"
kotlin-serialization = "1.6.0"
mockk = "1.13.8"
coroutines = "1.6.0"
ksp = "1.9.10-1.0.13"

compileSdk = "34"
minSdk = "24"
targetSdk = "34"
material = "1.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-sqlite = { module = "androidx.sqlite:sqlite-ktx", version.ref = "sqlite" }

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

androidx-datastore-prefs = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-prefs" }

androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "crypto" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

google-material = "com.google.android.material:material:1.9.0"

junit = { module = "junit:junit", version.ref = "junit" }
strikt-core = { module = "io.strikt:strikt-core", version.ref = "striktCore" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
gms-googleServices = { id = "com.google.gms.google-services", version.ref = "gms" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }