name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
    - uses: actions/checkout@v4
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Decode google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run unit tests
      run: ./gradlew test

     # Run Build Project
    - name: Build gradle project
      run: ./gradlew build
    - run: echo "Build status report=${{ job.status }}."

    - name: Check code
      run: ./gradlew check

    - name: Build release APK
      run: ./gradlew assembleRelease
