name: Android Setup
on:
  workflow_call: # Allows reusing this workflow in other workflows

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Export Environment Variables
        id: export_envs
        run: |
          echo "HIOR_PATH_R=${{ secrets.HIOR_PATH_R }}" >> $GITHUB_ENV
          echo "HIOR_KEY_PASS_R=${{ secrets.HIOR_KEY_PASS_R }}" >> $GITHUB_ENV
          echo "HIOR_STORE_PASS_R=${{ secrets.HIOR_STORE_PASS_R }}" >> $GITHUB_ENV
          echo "HIOR_ALIAS_R=${{ secrets.HIOR_ALIAS_R }}" >> $GITHUB_ENV
          echo "ENCODED_STRING_R=${{ secrets.HIOR_KEYSTORE_R }}" >> $GITHUB_ENV
          echo "HIOR_PATH_D=${{ secrets.HIOR_PATH_D }}" >> $GITHUB_ENV
          echo "HIOR_KEY_PASS_D=${{ secrets.HIOR_KEY_PASS_D }}" >> $GITHUB_ENV
          echo "HIOR_STORE_PASS_D=${{ secrets.HIOR_STORE_PASS_D }}" >> $GITHUB_ENV
          echo "HIOR_ALIAS_D=${{ secrets.HIOR_ALIAS_D }}" >> $GITHUB_ENV
          echo "ENCODED_STRING_D=${{ secrets.HIOR_KEYSTORE_D }}" >> $GITHUB_ENV
          echo "GOOGLE_SERVICES_JSON=${{ secrets.GOOGLE_SERVICES_JSON }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Decode google-services.json
        run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Restore release keystore.jks
        run: echo $ENCODED_STRING_R | base64 -d > ./release.keystore.jks

      - name: Restore debug keystore.jks
        run: echo $ENCODED_STRING_D | base64 -d > ./debug.keystore.jks