name: Build Project

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: android-setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/android-setup.yml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Gradle project
        run: ./gradlew build --no-daemon
