name: Build Project
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HIOR_PATH_R: ${{ secrets.HIOR_PATH_R }}
      HIOR_KEY_PASS_R: ${{ secrets.HIOR_KEY_PASS_R }}
      HIOR_STORE_PASS_R: ${{ secrets.HIOR_STORE_PASS_R }}
      HIOR_ALIAS_R: ${{ secrets.HIOR_ALIAS_R }}
      ENCODED_STRING_R: ${{ secrets.HIOR_KEYSTORE_R }}

      HIOR_PATH_D: ${{ secrets.HIOR_PATH_D }}
      HIOR_KEY_PASS_D: ${{ secrets.HIOR_KEY_PASS_D }}
      HIOR_STORE_PASS_D: ${{ secrets.HIOR_STORE_PASS_D }}
      HIOR_ALIAS_D: ${{ secrets.HIOR_ALIAS_D }}
      ENCODED_STRING_D: ${{ secrets.HIOR_KEYSTORE_D }}

      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/android-setup-composite-action

      - name: Decode google-services.json
        run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Restore release keystore.jks
        run: echo $ENCODED_STRING_R | base64 -d > ./release.keystore.jks

      - name: Restore debug keystore.jks
        run: echo $ENCODED_STRING_D | base64 -d > ./debug.keystore.jks

      - name: Assemble gradle fdroid project
        run: ./gradlew assembleFdroidDebug

      - name: Assemble gradle gplay project
        run: ./gradlew assembleGplayDebug