name: Build Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.HIOR_KEYSTORE_R }}
          DECODED_KEYSTORE_PATH: ${{ secrets.HIOR_KEYSTORE_PATH_R }}

          ENCODED_KEYSTORE_D: ${{ secrets.HIOR_KEYSTORE_D }}
          DECODED_KEYSTORE_PATH_D: ${{ secrets.HIOR_KEYSTORE_PATH_D }}
        run: |
            echo $ENCODED_KEYSTORE > keystore_base64.txt
            base64 -d keystore_base64.txt > $DECODED_KEYSTORE_PATH
            echo ENCODED_KEYSTORE_D > keystore_base64_d.txt
            base64 -d keystore_base64_d.txt > DECODED_KEYSTORE_PATH_D

      - name: Sign and Build Release Bundle
        env:
          HIOR_KEYSTORE_PATH_R: ${{ secrets.HIOR_KEYSTORE_PATH_R }}
          HIOR_KEY_PASS_R: ${{ secrets.HIOR_KEY_PASS_R }}
          HIOR_STORE_PASS_R: ${{ secrets.HIOR_STORE_PASS_R }}
          HIOR_ALIAS_R: ${{ secrets.HIOR_ALIAS_R }}
        run:
          ./gradlew bundleRelease

      - name: Sign and Build Release Bundle
        env:
          HIOR_KEYSTORE_PATH_R: ${{ secrets.HIOR_KEYSTORE_PATH_R }}
          HIOR_KEY_PASS_R: ${{ secrets.HIOR_KEY_PASS_R }}
          HIOR_STORE_PASS_R: ${{ secrets.HIOR_STORE_PASS_R }}
          HIOR_ALIAS_R: ${{ secrets.HIOR_ALIAS_R }}
        run:
          ./gradlew assembleRelease

      - name: Sign and Build Release Bundle
        env:
          HIOR_KEYSTORE_PATH_D: ${{ secrets.HIOR_KEYSTORE_PATH_D }}
          HIOR_KEY_PASS_D: ${{ secrets.HIOR_KEY_PASS_D }}
          HIOR_STORE_PASS_D: ${{ secrets.HIOR_STORE_PASS_D }}
          HIOR_ALIAS_D: ${{ secrets.HIOR_ALIAS_D }}
        run:
          ./gradlew assembleDebug

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build gradle project
        run: ./gradlew build