name: Code Analysis

on:
  pull_request:
    branches: [ "master" ]

jobs:
  detekt:
    runs-on: ubuntu-latest
    needs: android-setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/android-setup.yml

      - name: Run Detekt
        run: ./gradlew detekt

  ktlint:
    runs-on: ubuntu-latest
    needs: android-setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/android-setup.yml

      - name: Run Ktlint
        run: ./gradlew ktlintCheck
