name: Code Analysis
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    env:
      HIOR_PATH_R: ${{ secrets.HIOR_PATH_R }}
      HIOR_KEY_PASS_R: ${{ secrets.HIOR_KEY_PASS_R }}
      HIOR_STORE_PASS_R: ${{ secrets.HIOR_STORE_PASS_R }}
      HIOR_ALIAS_R: ${{ secrets.HIOR_ALIAS_R }}
      ENCODED_STRING_R: ${{ secrets.HIOR_KEYSTORE_R }}

      HIOR_PATH_D: ${{ secrets.HIOR_PATH_D }}
      HIOR_KEY_PASS_D: ${{ secrets.HIOR_KEY_PASS_D }}
      HIOR_STORE_PASS_D: ${{ secrets.HIOR_STORE_PASS_D }}
      HIOR_ALIAS_D: ${{ secrets.HIOR_ALIAS_D }}
      ENCODED_STRING_D: ${{ secrets.HIOR_KEYSTORE_D }}

      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Setup Android Environment
        uses: ./.github/actions/android-setup-composite-action

      - name: Decode google-services.json
        run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Restore release keystore.jks
        run: echo $ENCODED_STRING_R | base64 -d > ./release.keystore.jks

      - name: Restore debug keystore.jks
        run: echo $ENCODED_STRING_D | base64 -d > ./debug.keystore.jks

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Run tests and generate Aggregated JaCoCo report
        run: ./gradlew test jacocoAggregatedReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./build/reports/jacoco/jacocoAggregatedReport/jacocoTestReport.xml
          fail_ci_if_error: true
