name: Create PR for Release

on:
 push:
    branches:
      - release/*

jobs:
 create-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create PR
        uses: Songmu/tagpr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: ${{ github.ref }}
