name: Unit Tests

on:
  pull_request:
    branches: [ "master" ]

env:
  HIOR_PATH_R: ${{ secrets.HIOR_PATH_R }}
  HIOR_KEY_PASS_R: ${{ secrets.HIOR_KEY_PASS_R }}
  HIOR_STORE_PASS_R: ${{ secrets.HIOR_STORE_PASS_R }}
  HIOR_ALIAS_R: ${{ secrets.HIOR_ALIAS_R }}
  ENCODED_STRING_R: ${{ secrets.HIOR_KEYSTORE_R }}
  HIOR_PATH_D: ${{ secrets.HIOR_PATH_D }}
  HIOR_KEY_PASS_D: ${{ secrets.HIOR_KEY_PASS_D }}
  HIOR_STORE_PASS_D: ${{ secrets.HIOR_STORE_PASS_D }}
  HIOR_ALIAS_D: ${{ secrets.HIOR_ALIAS_D }}
  ENCODED_STRING_D: ${{ secrets.HIOR_KEYSTORE_D }}
  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    needs: android-setup
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/android-setup.yml  # Reuse Android setup

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --no-daemon
